# taken and modified from https://github.com/philen/scala-jpackage-workflow-demo
# jpackage docs:  https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html
# jpackage jep: https://openjdk.java.net/jeps/392
name: Build for Release

on:
  pull_request:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

env:
  pkg-assembly: 'krystal-bull-assembly-0.1.jar'
  pkg-name: 'krystalbull'
  pkg-version: '0.1'

jobs:
  fat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build fat jar
        run: sbt assembly
      - name: Upload fat jar
        uses: actions/upload-artifact@v1
        with:
          name: jars
          path: "target/scala-2.13/"
  osx:
    needs: fat
    runs-on: [macos-latest]
    steps:
      - name: Import cert to keychain
        uses: apple-actions/import-codesign-certs@v1
        env:
          CERTIFICATES_P12: ${{secrets.CERTIFICATES_P12}}
          CERTIFICATES_P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        with:
          p12-file-base64: "MIIMpwIBAzCCDG4GCSqGSIb3DQEHAaCCDF8EggxbMIIMVzCCBscGCSqGSIb3DQEHBqCCBrgwgga0AgEAMIIGrQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIfrWZF8jAWVACAggAgIIGgKigUi7/GDGg8Bk8n0Iige97tLYRbxEYRKz63XsEwjg8CqbMEzsk8/royGr5AZeaNV9PbsTeAx1zfQBpjtqYYgssmOETh9CWse4CXLC2XZO9UZB34M4Pl6MZXfmXHY7ttSUNA74UJvQha/28aY7yobWchv6gu4Wu6L2VYUZwjXT++ggGHRde3k8C6mCACf5t21dKIISwFIf4dxwN72M67rYex9yWY7mTzVld9a7nSpEG52sAZkH/ysslezfELyy1D8dvPae3T9qnCGE+GHyQvBzxtGx9T0iS5bUd4VdJTpPhXx3UH/NrSLcTlRV2qFWzByUkCBepUzVaK/nKU8l3xnzLhOXXQ7JMvj0K5MN2x+y2/sEr3qQJ1W+2UUXvm/U66P1LOV8dhuSDxSSdW6p8uPtyQnb9esKM60HeMbykWhN7EgiueHKG1DRg1q0fO49BC/YvhrOtDCysqpRKSq8wUbC/TGw/TIkVJrJDVw/QAO8jA2SNVgeRwUWsisU6BjEkHG0rZqJ1oqwU0aFw07no/1Jqi4RLuQ+xiKSrWsZgnK17jPy/T39C789YXGB9XJzcYbVlavEjxWM7UFu/WlYuZgxl9Ar8sfUftBpCKs6MhrAYjbmoJob7M+GD0XCzrDXU3s5DkaQApuIZn3KMGyaMuVJz0BkKPmLpaWcH1BSn/fn68l4MZXnoBQ/EJXhYoGkMCIXBY8SfkR65274P0SXnMl+9zc2JH+OR97JGFlklKDZ7o9f/gkw63lYOI3W1hOAqm4aNZDQegIg0OTesTET5g6NBJG5Due97FWczqp44YClBiUkmpdrdX1W+CctjG3cvPdlPEmux5oaYJHnSnaf7PnK/3sOGukGqn6HU8bQTtOYof9LBUmPw8TCLmVSBvdH7P93Bjrj0KPMniAGrK0vghnOK2omGZ63+O+6MQLX29Iw8ew5/IgbkKQj9xMXOfi3nEpQnjs2hGfesGpM/ilKxB+c/wUN4RABuGMQ8gnUoKvLt3obNq4RRw4cwp/I8eyWT+4qRcPdDiZikNAhsvfWsLyFn3yOv/wmfx1dekdkWkwJ5aNTt1N54smVSw7pp7yDqxMpJXiKHP5R//rNZ3GhG+d0A2oN8w0ZXFJWyotHWI9njI9VdFn0Zv67ipfrzt9D7fYM755tNbm5dY5XuhhIlVDeggWko8A9ym4gnhXTwn9189ujYUUz/vyRusoNSbgBbIXx18Hns2UQleRQVQaHIj+cFONxN1bzkw6mtFN+4Z3C2cUh4RI0mD/fqwH18OEpK/VRRY1iFIh0NMgKOhSbYjZZfuZ2EGQCue1KaZUvcQL/KQRBuQvwx2T5RcCvATTgSTMd8XWg0VaT8duzbpsoimBy8yudSr1Ln49rE80T3zmdhAjDKFrINm7h2MWAbmSwrZeFLVrU8er6REYxj3U7FRexgNvw7XEzlXr0XzEUIzNkG5adeuM2ME5ZYqDo1wW6eYIhs84cdiCLTUm9M/iB68I01R3D/RK8y5HZKi6F2Wd8yOgO8sPdgoIkLwyUJECbPfRAppIXYaJVJ5M1o8TmylEqB3TF6Ys1XqpOdDqNz44lViKQ0pbjbirILjlyVBzUw3yzkiF7qpnTqPUmRBSbQnpjb8d3rXJu8V8Antmn0q+s4PfXViqr6n4u7RW/Fi4TUVp+0U1htiVlseLnM0O0hLbKmZP2JZJ8wBPvJOmyT3DPMyrJXK++1xufvlCM5ulilPFO2lwmGgNtXfXJCoJ0v0VG3iFTBH3qIcgl2q4VTl/DVLf1gTHnxwHVMjWjkWf0gVp+BSdvK2M1gRQA1vbxajG81sYzpNpIs+gMGzFEMw+j7hh2Y+2L2LwYiGru73STqtbUZc8wDe3Sm19Iu064ynosi+1AUij3bZSPOLXwJ43PafJijSvUOrCuLyRPPITXl32xS7WVXtVrTZbTAiTlXi0OyQFQ9i5CgVR3BG4W4j0BNlK+4D65N9xo9FB1XZe5aw0HZysnV0LFxiryOD4PDOjP2a3KWJM2PwK9dwws469mXnLoH9oJVAF8SUbgawPpCroFoOaCau3V3cKgerJ2SYnEARl3LjIJtK+0rjl4H6iWDXk2wAlkaAFKz7i1O5BBmF9x4ixmJdZJ3I2yRXMLFSUQEHUSSgLkeYTINSHq0xDH0L0kgnDpFVaXsQYE6tIgQRYgXOrAvQcelLS8e28D9ZuznDiBZ+QlllJC7osMvamJ9MIIFiAYJKoZIhvcNAQcBoIIFeQSCBXUwggVxMIIFbQYLKoZIhvcNAQwKAQKgggTuMIIE6jAcBgoqhkiG9w0BDAEDMA4ECG77TC5vRxc1AgIIAASCBMjCsZBlF2LUWadtXPgANm9Bb1AIpnM4ynEjZs/N5efOUDMtD/Yo83AyXQdi4ruPwYQ0faOngcCx5deQAzQFhQumIXv74kmyBKOPPrgeNeJRMPJ+cqOCR5VRJ0MWfuPdZoYQ9/tJ/XH7lUIuUKQQMIKTX9zcW/QS9Acw3muRgq7LS2ieMF+JRoWjkVWFAUHc/wtesIjhqGfIeh0fd1FPx2NFSqba0Twj5E9UPuX/zgGYdpTndHfiyAnWy71PWS2LDN9dDlmmjM29SdfyAwnePc2b3PcHatyByoh2A//PM0OHtyXrLeHXnCSZGVEwcOoxBRxhAEbK5fQxuHMzxe5/lo5CVfvGfUSMKonbWN5wT60LF3PQ0MWn6L796jSZkGRR1NSs+TVWmuYetz2K097fUon1g2aBTNEUA1HNm3V6ouTTdUCgDILUDf+3WiAqyJTEinajF9WNgyhqG/GMqshk6FwQ/jPKekrhzVtzpI3cuWPes1iZWL2JUGkWqI7cSjp9PhS2hSA9lDRSbg7cJqqUGc0lTrKWB+c5/i/fa5bhaPlPDIjIHQtuUGHgZikIZeMrO99UPTOifoffVWUh3tdWmqa5NCLjDTRjqR9xcP3Zg/jWzQXYBiteIcXjDW1f3lrXhnIJY04fPnxH7Hgl3+sNBgsJpa1OZua4HvO1vOxmkqgJAxTl65Gs/KRPX0zyePeGLUoFAgV7u7pzpjKN05E49lM7zMA/vvs2gJfTy6nYa/AnAXUze8bmqpjLqCwP/J2ZXWqk49UseG/gSzktt9CkfdbWJ5YF1/6SJb8TcYYdkUIxjOq+VQPdk6LUA/eUhRiIBrYUErRmoS20YCzguDSw9xvMu8Bpttp27131Q9a0OG/ZoMc5KFX+M3KarXvGd14468yomM328Fl/A5hurKpJAbhZJl2gXhMJaunXX6zFsWcFbw4uiyC+YHXW9EwQl4GhgVrMel5JogK1Qtal8UFYTtyucc/D+1atgxn0vgtFic55k2oGJ8/xXJhEEAgcwpQjMn0/+gRpuPzJlSGm7Q0zsQgfMLWReY+SGTG3CzgoY9gKQwK4B/uVIdPRYhd0qa32Blu52QSJZi+sdR0b2N0Gy2Dnfkhi4Zx5lKOxx0Vma0jyDK0/R6ORrgjBz2HBQseq4sq+M3As9DkDNrR/iHBCYm64lYOrFL6w6HfkR16ZGLkKAOfo16LrdaH5LDco3ey2fULc8AkIgQjTTM5gzAKgwD8JNmtZoRaCbUfmd2THh8aZuxfHeEs9xp1XrAu6B2cCU0RbQHsDoUTEV8TLDzMIU5JNXPlzkDouLimd5u1P1HPbx1noyGdqkEC77UZQ3tIqNTOLe5GiDh2XwSqGB700gv5ImbA4J7eXbTPo69BzhAt3GL9maRIuQ00lWG4J2XwDE23E4RUqVG6hPE9ksS5x6xiAbvoQ9ySioSWQBfFvLjd1wBuKqJJJBopkIkBi//oNDTq9URWKTCreoDDN/QVPTVHa0uI6F3NxDapjDerUYfJ9EWCjkTl+WvJdAGGybNoRWspceES4vTMwlZoBIfEXDpVEpFtGZuzFxMJ1TNvHg5z8dTeBaSdxWWnsXmrZoFvTD4NVIyLzSXuIcfiEjY0zV0m9k5Ab2c7YtmIxbDBFBgkqhkiG9w0BCRQxOB42AEsAcgB5AHMAdABhAGwAIABCAHUAbABsACAARwBpAHQAaAB1AGIAIABBAGMAdABpAG8AbgBzMCMGCSqGSIb3DQEJFTEWBBTQg59hsI/7yK4KCASK/isNvB89WzAwMCEwCQYFKw4DAhoFAAQU8Y57AyofOFr+ugH4f402cytpTOIECBo9BCXgBCgMAgEB"
          p12-password: $CERTIFICATES_P12_PASSWORD
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.0'
          java-package: jdk
          architecture: x64
      - name: Download fat jar
        uses: actions/download-artifact@v1
        with:
          name: jars
          path: "target/scala-2.13"
      # https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
      # security create-keychain -p $MACOS_CERTIFICATE_PWD build.keychain security default-keychain -s build.keychain
      - name: Add cert to keychain and unlock keychain
        env:
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERT_FILE_PATH: ${{ steps.write_file.outputs.filePath }}
        run: |
          echo "Hello world"
          security unlock-keychain -p $MACOS_CERTIFICATE_PWD signing_temp.keychain
          security import $MACOS_CERT_FILE_PATH -k signing_temp.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security find-identity -v
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k MACOS_CERTIFICATE_PWD signing_temp.keychain
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Package jar as dmg installer
        run: "jpackage --name ${{ env.pkg-name }} --app-version ${{ env.pkg-version }} --type dmg -i target/scala-2.13/ --main-class com.krystal.bull.gui.GUI --main-jar ${{ env.pkg-assembly }} --icon src/main/resources/icons/krystal_bull.icns --mac-sign --mac-signing-key-user-name \"Developer ID Application: Chris Stewart (9ZG3GPKHX8)\""
      - name: View Artifacts
        run: ls -l
      - name: View Artifact name
        run: echo "${{ env.pkg-name }}-${{ env.pkg-version }}"
      - name: Upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: dmgs
          path: "${{ env.pkg-name }}-${{ env.pkg-version }}.dmg"
  windows:
    needs: fat
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16.0.1'
          java-package: jdk
          architecture: x64
      - name: Download fat jar
        uses: actions/download-artifact@v1
        with:
          name: jars
          path: "target/scala-2.13"
      - name: Package jar as msi
        run: "jpackage --win-shortcut --win-menu --win-menu-group 'Krystal Bull' --name ${{env.pkg-name}} --app-version ${{ env.pkg-version }} --type msi -i target/scala-2.13/ --main-class com.krystal.bull.gui.GUI --main-jar ${{ env.pkg-assembly }} --icon src/main/resources/icons/krystal_bull.ico --verbose"
      - name: View artifacts
        run: dir
      - name: Upload installer
        uses: actions/upload-artifact@v1
        with:
          name: msis
          path: "${{ env.pkg-name }}-${{ env.pkg-version }}.msi"
  linux:
    needs: fat
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.0'
          java-package: jdk
          architecture: x64
      - name: Download fat jar
        uses: actions/download-artifact@v1
        with:
          name: jars
          path: "target/scala-2.13"
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Package jar as debian package
        run: "jpackage --linux-shortcut --name ${{ env.pkg-name }} --app-version ${{ env.pkg-version }} --type deb -i target/scala-2.13/ --main-class com.krystal.bull.gui.GUI --main-jar ${{ env.pkg-assembly }} --icon src/main/resources/icons/krystal_bull.png"
      - name: View Artifacts
        run: ls -l
      - name: Print working dir
        run: pwd
      - name: Upload deb
        uses: actions/upload-artifact@v1
        with:
          name : debs
          path: "${{ env.pkg-name }}_${{ env.pkg-version }}-1_amd64.deb"
